SRCS += \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIInfoHelper.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIInfoProviders.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIInfoLabel.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIInfoBool.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIInfoColor.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/AddonsGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/GUIControlsGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/LibraryGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/MusicGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/PicturesGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/PlayerGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/SkinGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/SystemGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/VideoGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/VisualisationGUIInfo.cpp \
	$(CURDIR)/xbmc/guilib/guiinfo/WeatherGUIInfo.cpp
