SRCS += \
	$(CURDIR)/xbmc/platform/xbox/AudioContext.cpp \
	$(CURDIR)/xbmc/platform/xbox/CPUInfoXbox.cpp \
	$(CURDIR)/xbmc/platform/xbox/MessagePrinter.cpp \
	$(CURDIR)/xbmc/platform/xbox/strptime.cpp \
	$(CURDIR)/xbmc/platform/xbox/XBOXUtil.cpp

include $(CURDIR)/xbmc/platform/xbox/filesystem/Makefile
include $(CURDIR)/xbmc/platform/xbox/storage/Makefile
