SRCS += \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryCleaningJob.cpp \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryJob.cpp \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryMarkWatchedJob.cpp \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryProgressJob.cpp \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryRefreshingJob.cpp \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryScanningJob.cpp \
	$(CURDIR)/xbmc/video/jobs/VideoLibraryResetResumePointJob.cpp
