SRCS += \
	$(CURDIR)/xbmc/utils/Archive.cpp \
	$(CURDIR)/xbmc/utils/auto_buffer.cpp \
	$(CURDIR)/xbmc/utils/JobManager.cpp \
	$(CURDIR)/xbmc/utils/Locale.cpp \
	$(CURDIR)/xbmc/utils/log.cpp \
	$(CURDIR)/xbmc/utils/Speed.cpp \
	$(CURDIR)/xbmc/utils/StringUtils.cpp \
	$(CURDIR)/xbmc/utils/Temperature.cpp \
	$(CURDIR)/xbmc/utils/TimeUtils.cpp \
	$(CURDIR)/xbmc/utils/URIUtils.cpp \
	$(CURDIR)/xbmc/utils/UrlOptions.cpp \
	$(CURDIR)/xbmc/utils/Variant.cpp
