SRCS += \
	$(CURDIR)/xbmc/utils/Archive.cpp \
	$(CURDIR)/xbmc/utils/auto_buffer.cpp \
	$(CURDIR)/xbmc/utils/BitstreamStats.cpp \
	$(CURDIR)/xbmc/utils/CharsetConverter.cpp \
	$(CURDIR)/xbmc/utils/CharsetDetection.cpp \
	$(CURDIR)/xbmc/utils/JobManager.cpp \
	$(CURDIR)/xbmc/utils/Locale.cpp \
	$(CURDIR)/xbmc/utils/log.cpp \
	$(CURDIR)/xbmc/utils/md5.cpp \
	$(CURDIR)/xbmc/utils/Observer.cpp \
	$(CURDIR)/xbmc/utils/POUtils.cpp \
	$(CURDIR)/xbmc/utils/RegExp.cpp \
	$(CURDIR)/xbmc/utils/Speed.cpp \
	$(CURDIR)/xbmc/utils/StringUtils.cpp \
	$(CURDIR)/xbmc/utils/StringValidation.cpp \
	$(CURDIR)/xbmc/utils/Temperature.cpp \
	$(CURDIR)/xbmc/utils/TimeUtils.cpp \
	$(CURDIR)/xbmc/utils/URIUtils.cpp \
	$(CURDIR)/xbmc/utils/UrlOptions.cpp \
	$(CURDIR)/xbmc/utils/Utf8Utils.cpp \
	$(CURDIR)/xbmc/utils/Variant.cpp \
	$(CURDIR)/xbmc/utils/XBMCTinyXML.cpp \
	$(CURDIR)/xbmc/utils/XMLUtils.cpp
