SRCS += \
	$(CURDIR)/xbmc/utils/auto_buffer.cpp \
	$(CURDIR)/xbmc/utils/log.cpp \
	$(CURDIR)/xbmc/utils/StringUtils.cpp \
	$(CURDIR)/xbmc/utils/URIUtils.cpp \
	$(CURDIR)/xbmc/utils/UrlOptions.cpp \
	$(CURDIR)/xbmc/utils/Variant.cpp
