SRCS += \
	$(CURDIR)/xbmc/playlists/PlayListB4S.cpp \
	$(CURDIR)/xbmc/playlists/PlayList.cpp \
	$(CURDIR)/xbmc/playlists/PlayListFactory.cpp \
	$(CURDIR)/xbmc/playlists/PlayListM3U.cpp \
	$(CURDIR)/xbmc/playlists/PlayListPLS.cpp \
	$(CURDIR)/xbmc/playlists/PlayListURL.cpp \
	$(CURDIR)/xbmc/playlists/PlayListWPL.cpp \
	$(CURDIR)/xbmc/playlists/PlayListXML.cpp \
	$(CURDIR)/xbmc/playlists/PlayListXSPF.cpp \
	$(CURDIR)/xbmc/playlists/SmartPlayList.cpp \
	$(CURDIR)/xbmc/playlists/SmartPlaylistFileItemListModifier.cpp
