SRCS += \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNode.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeEpisodes.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeGrouped.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeInProgressTvShows.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeMoviesOverview.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeMusicVideosOverview.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeOverview.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeRecentlyAddedEpisodes.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeRecentlyAddedMovies.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeRecentlyAddedMusicVideos.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeRoot.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeSeasons.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeTitleMovies.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeTitleMusicVideos.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeTitleTvShows.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeTvShowsOverview.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/QueryParams.cpp
