SRCS += \
	$(CURDIR)/xbmc/settings/dialogs/GUIDialogLibExportSettings.cpp \
	$(CURDIR)/xbmc/settings/dialogs/GUIDialogSettingsBase.cpp \
	$(CURDIR)/xbmc/settings/dialogs/GUIDialogSettingsManagerBase.cpp \
	$(CURDIR)/xbmc/settings/dialogs/GUIDialogSettingsManualBase.cpp
