SRCS += \
	$(CURDIR)/xbmc/input/ButtonTranslator.cpp \
	$(CURDIR)/xbmc/input/InputCodingTableBasePY.cpp \
	$(CURDIR)/xbmc/input/InputCodingTableFactory.cpp \
	$(CURDIR)/xbmc/input/InputCodingTableKorean.cpp \
	$(CURDIR)/xbmc/input/Key.cpp \
	$(CURDIR)/xbmc/input/KeyboardLayout.cpp \
	$(CURDIR)/xbmc/input/KeyboardLayoutManager.cpp \
	$(CURDIR)/xbmc/input/XBMC_keytable.cpp
