SRCS += \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbum.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbumRecentlyAdded.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbumRecentlyAddedSong.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbumRecentlyPlayed.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbumRecentlyPlayedSong.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbumTop100.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeAlbumTop100Song.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeArtist.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeDiscs.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNode.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeGrouped.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeOverview.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeRoot.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeSingles.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeSong.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeSongTop100.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/DirectoryNodeTop100.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/QueryParams.cpp
