SRCS += \
	$(CURDIR)/xbmc/interfaces/AnnouncementManager.cpp

include $(CURDIR)/xbmc/interfaces/builtins/Makefile
include $(CURDIR)/xbmc/interfaces/generic/Makefile
include $(CURDIR)/xbmc/interfaces/info/Makefile
