SRCS += \
	$(CURDIR)/xbmc/listproviders/DirectoryProvider.cpp \
	$(CURDIR)/xbmc/listproviders/IListProvider.cpp \
	$(CURDIR)/xbmc/listproviders/MultiProvider.cpp \
	$(CURDIR)/xbmc/listproviders/StaticProvider.cpp
