SRCS += \
	$(CURDIR)/xbmc/music/Album.cpp \
	$(CURDIR)/xbmc/music/Artist.cpp \
	$(CURDIR)/xbmc/music/ContextMenus.cpp \
	$(CURDIR)/xbmc/music/GUIViewStateMusic.cpp \
	$(CURDIR)/xbmc/music/MusicDatabase.cpp \
	$(CURDIR)/xbmc/music/MusicDbUrl.cpp \
	$(CURDIR)/xbmc/music/MusicInfoLoader.cpp \
	$(CURDIR)/xbmc/music/MusicLibraryQueue.cpp \
	$(CURDIR)/xbmc/music/MusicThumbLoader.cpp \
	$(CURDIR)/xbmc/music/MusicUtils.cpp \
	$(CURDIR)/xbmc/music/Song.cpp

include $(CURDIR)/xbmc/music/dialogs/Makefile
include $(CURDIR)/xbmc/music/infoscanner/Makefile
include $(CURDIR)/xbmc/music/jobs/Makefile
include $(CURDIR)/xbmc/music/tags/Makefile
include $(CURDIR)/xbmc/music/windows/Makefile
