SRCS += \
	$(CURDIR)/xbmc/favourites/ContextMenus.cpp \
	$(CURDIR)/xbmc/favourites/GUIDialogFavourites.cpp \
	$(CURDIR)/xbmc/favourites/GUIViewStateFavourites.cpp \
	$(CURDIR)/xbmc/favourites/GUIWindowFavourites.cpp \
	$(CURDIR)/xbmc/favourites/FavouritesService.cpp \
	$(CURDIR)/xbmc/favourites/FavouritesURL.cpp \
	$(CURDIR)/xbmc/favourites/FavouritesUtils.cpp
