SRCS += \
	$(CURDIR)/xbmc/guilib/GraphicContext.cpp \
	$(CURDIR)/xbmc/guilib/GUIAudioManager.cpp \
	$(CURDIR)/xbmc/guilib/GUIMessage.cpp \
	$(CURDIR)/xbmc/guilib/GUISound.cpp \
	$(CURDIR)/xbmc/guilib/LocalizeStrings.cpp \
	$(CURDIR)/xbmc/guilib/Texture.cpp \
	$(CURDIR)/xbmc/guilib/TextureManager.cpp
