SRCS += \
	$(CURDIR)/xbmc/application/Application.cpp \
	$(CURDIR)/xbmc/application/ApplicationActionListeners.cpp \
	$(CURDIR)/xbmc/application/ApplicationPlayer.cpp \
	$(CURDIR)/xbmc/application/ApplicationSkinHandling.cpp \
	$(CURDIR)/xbmc/application/AppParams.cpp
