SRCS += \
	$(CURDIR)/xbmc/filesystem/AddonsDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/CacheStrategy.cpp \
	$(CURDIR)/xbmc/filesystem/CircularCache.cpp \
	$(CURDIR)/xbmc/filesystem/CurlFile.cpp \
	$(CURDIR)/xbmc/filesystem/Directory.cpp \
	$(CURDIR)/xbmc/filesystem/DirectoryCache.cpp \
	$(CURDIR)/xbmc/filesystem/DirectoryFactory.cpp \
	$(CURDIR)/xbmc/filesystem/File.cpp \
	$(CURDIR)/xbmc/filesystem/FileCache.cpp \
	$(CURDIR)/xbmc/filesystem/FileDirectoryFactory.cpp \
	$(CURDIR)/xbmc/filesystem/FileFactory.cpp \
	$(CURDIR)/xbmc/filesystem/IDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/IFile.cpp \
	$(CURDIR)/xbmc/filesystem/MultiPathDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/MultiPathFile.cpp \
	$(CURDIR)/xbmc/filesystem/OverrideFile.cpp \
	$(CURDIR)/xbmc/filesystem/SpecialProtocol.cpp \
	$(CURDIR)/xbmc/filesystem/StackDirectory.cpp
