SRCS += \
	$(CURDIR)/xbmc/filesystem/AddonsDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/CacheStrategy.cpp \
	$(CURDIR)/xbmc/filesystem/CircularCache.cpp \
	$(CURDIR)/xbmc/filesystem/CurlFile.cpp \
	$(CURDIR)/xbmc/filesystem/Directory.cpp \
	$(CURDIR)/xbmc/filesystem/DirectoryCache.cpp \
	$(CURDIR)/xbmc/filesystem/DirectoryFactory.cpp \
	$(CURDIR)/xbmc/filesystem/DirectoryHistory.cpp \
	$(CURDIR)/xbmc/filesystem/File.cpp \
	$(CURDIR)/xbmc/filesystem/FileCache.cpp \
	$(CURDIR)/xbmc/filesystem/FileDirectoryFactory.cpp \
	$(CURDIR)/xbmc/filesystem/FileFactory.cpp \
	$(CURDIR)/xbmc/filesystem/IDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/IFile.cpp \
	$(CURDIR)/xbmc/filesystem/MultiPathDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/MultiPathFile.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/MusicDatabaseFile.cpp \
	$(CURDIR)/xbmc/filesystem/MusicFileDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/MusicSearchDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/OverrideFile.cpp \
	$(CURDIR)/xbmc/filesystem/PlaylistDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/PlaylistFileDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/PluginDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/SmartPlaylistDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/SourcesDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/SpecialProtocol.cpp \
	$(CURDIR)/xbmc/filesystem/StackDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/VideoDatabaseFile.cpp \
	$(CURDIR)/xbmc/filesystem/VirtualDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/ZipDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/ZipFile.cpp

include $(CURDIR)/xbmc/filesystem/MusicDatabaseDirectory/Makefile
include $(CURDIR)/xbmc/filesystem/VideoDatabaseDirectory/Makefile
