SRCS += \
	$(CURDIR)/xbmc/filesystem/DirectoryFactory.cpp \
	$(CURDIR)/xbmc/filesystem/File.cpp \
	$(CURDIR)/xbmc/filesystem/FileFactory.cpp \
	$(CURDIR)/xbmc/filesystem/IDirectory.cpp \
	$(CURDIR)/xbmc/filesystem/IFile.cpp
