SRCS += \
	$(CURDIR)/xbmc/settings/lib/ISetting.cpp \
	$(CURDIR)/xbmc/settings/lib/ISettingControl.cpp \
	$(CURDIR)/xbmc/settings/lib/Setting.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingCategoryAccess.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingConditions.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingDependency.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingSection.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingsManager.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingRequirement.cpp \
	$(CURDIR)/xbmc/settings/lib/SettingUpdate.cpp
