SRCS += \
	$(CURDIR)/xbmc/platform/win32/CharsetConverter.cpp

include $(CURDIR)/xbmc/platform/win32/filesystem/Makefile
include $(CURDIR)/xbmc/platform/win32/threads/Makefile
include $(CURDIR)/xbmc/platform/win32/utils/Makefile
