SRCS += \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogAudioSettings.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogFullScreenInfo.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogSubtitles.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogTeletext.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogVideoBookmarks.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogVideoInfo.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogVideoOSD.cpp \
	$(CURDIR)/xbmc/video/dialogs/GUIDialogVideoSettings.cpp
