SRCS += \
	$(CURDIR)/xbmc/interfaces/generic/ILanguageInvoker.cpp \
	$(CURDIR)/xbmc/interfaces/generic/LanguageInvokerThread.cpp \
	$(CURDIR)/xbmc/interfaces/generic/RunningScriptObserver.cpp \
	$(CURDIR)/xbmc/interfaces/generic/ScriptInvocationManager.cpp \
	$(CURDIR)/xbmc/interfaces/generic/ScriptRunner.cpp
