SRCS += \
	$(CURDIR)/xbmc/windows/GUIMediaWindow.cpp \
	$(CURDIR)/xbmc/windows/GUIWindowHome.cpp \
	$(CURDIR)/xbmc/windows/GUIWindowLoginScreen.cpp \
	$(CURDIR)/xbmc/windows/GUIWindowSplash.cpp \
	$(CURDIR)/xbmc/windows/GUIWindowStartup.cpp \
	$(CURDIR)/xbmc/windows/GUIWindowSystemInfo.cpp
