SRCS += \
	$(CURDIR)/xbmc/addons/gui/GUIDialogAddonInfo.cpp \
	$(CURDIR)/xbmc/addons/gui/GUIDialogAddonSettings.cpp \
	$(CURDIR)/xbmc/addons/gui/GUIHelpers.cpp \
	$(CURDIR)/xbmc/addons/gui/GUIViewStateAddonBrowser.cpp \
	$(CURDIR)/xbmc/addons/gui/GUIWindowAddonBrowser.cpp
