SRCS += \
	$(CURDIR)/music/infoscanner/MusicAlbumInfo.cpp \
	$(CURDIR)/music/infoscanner/MusicArtistInfo.cpp \
	$(CURDIR)/music/infoscanner/MusicInfoScanner.cpp \
	$(CURDIR)/music/infoscanner/MusicInfoScraper.cpp
