SRCS += \
	$(CURDIR)/music/jobs/MusicLibraryJob.cpp \
	$(CURDIR)/music/jobs/MusicLibraryProgressJob.cpp \
	$(CURDIR)/music/jobs/MusicLibraryCleaningJob.cpp \
	$(CURDIR)/music/jobs/MusicLibraryExportJob.cpp \
	$(CURDIR)/music/jobs/MusicLibraryImportJob.cpp \
	$(CURDIR)/music/jobs/MusicLibraryScanningJob.cpp
