SRCS += \
	$(CURDIR)/xbmc/music/windows/GUIWindowMusicBase.cpp \
	$(CURDIR)/xbmc/music/windows/GUIWindowMusicNav.cpp \
	$(CURDIR)/xbmc/music/windows/GUIWindowMusicPlaylist.cpp \
	$(CURDIR)/xbmc/music/windows/GUIWindowMusicPlaylistEditor.cpp \
	$(CURDIR)/xbmc/music/windows/GUIWindowVisualisation.cpp \
	$(CURDIR)/xbmc/music/windows/MusicFileItemListModifier.cpp
