SRCS += \
	$(CURDIR)/xbmc/cores/playercorefactory/PlayerCoreConfig.cpp \
	$(CURDIR)/xbmc/cores/playercorefactory/PlayerCoreFactory.cpp \
	$(CURDIR)/xbmc/cores/playercorefactory/PlayerSelectionRule.cpp
