SRCS += \
	$(CURDIR)/xbmc/video/tags/VideoInfoTagLoaderFactory.cpp \
	$(CURDIR)/xbmc/video/tags/VideoTagLoaderFFmpeg.cpp \
	$(CURDIR)/xbmc/video/tags/VideoTagLoaderNFO.cpp \
	$(CURDIR)/xbmc/video/tags/VideoTagLoaderPlugin.cpp
