SRCS += \
	$(CURDIR)/xbmc/interfaces/builtins/AddonBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/ApplicationBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/Builtins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/CECBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/GUIBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/GUIControlBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/GUIContainerBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/LibraryBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/OpticalBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/PictureBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/PlayerBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/ProfileBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/SkinBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/SystemBuiltins.cpp \
	$(CURDIR)/xbmc/interfaces/builtins/WeatherBuiltins.cpp
