SRCS += \
	$(CURDIR)/xbmc/video/windows/GUIWindowVideoBase.cpp \
	$(CURDIR)/xbmc/video/windows/GUIWindowVideoNav.cpp \
	$(CURDIR)/xbmc/video/windows/GUIWindowVideoPlaylist.cpp \
	$(CURDIR)/xbmc/video/windows/VideoFileItemListModifier.cpp
