SRCS += \
	$(CURDIR)/xbmc/addons/addoninfo/AddonExtensions.cpp \
	$(CURDIR)/xbmc/addons/addoninfo/AddonInfo.cpp \
	$(CURDIR)/xbmc/addons/addoninfo/AddonInfoBuilder.cpp \
	$(CURDIR)/xbmc/addons/addoninfo/AddonType.cpp
