SRCS += \
	$(CURDIR)/xbmc/dbwrappers/Database.cpp \
	$(CURDIR)/xbmc/dbwrappers/DatabaseQuery.cpp \
	$(CURDIR)/xbmc/dbwrappers/dataset.cpp \
	$(CURDIR)/xbmc/dbwrappers/qry_dat.cpp \
	$(CURDIR)/xbmc/dbwrappers/sqlitedataset.cpp
