SRCS += \
	$(CURDIR)/xbmc/video/Bookmark.cpp \
	$(CURDIR)/xbmc/video/ContextMenus.cpp \
	$(CURDIR)/xbmc/video/GUIViewStateVideo.cpp \
	$(CURDIR)/xbmc/video/PlayerController.cpp \
	$(CURDIR)/xbmc/video/Teletext.cpp \
	$(CURDIR)/xbmc/video/VideoDatabase.cpp \
	$(CURDIR)/xbmc/video/VideoDbUrl.cpp \
	$(CURDIR)/xbmc/video/VideoInfoDownloader.cpp \
	$(CURDIR)/xbmc/video/VideoInfoScanner.cpp \
	$(CURDIR)/xbmc/video/VideoInfoTag.cpp \
	$(CURDIR)/xbmc/video/VideoLibraryQueue.cpp \
	$(CURDIR)/xbmc/video/VideoThumbLoader.cpp \
	$(CURDIR)/xbmc/video/VideoUtils.cpp \
	$(CURDIR)/xbmc/video/ViewModeSettings.cpp

include $(CURDIR)/xbmc/video/dialogs/Makefile
include $(CURDIR)/xbmc/video/jobs/Makefile
include $(CURDIR)/xbmc/video/tags/Makefile
include $(CURDIR)/xbmc/video/windows/Makefile
