SRCS += \
	$(CURDIR)/music/dialogs/GUIDialogInfoProviderSettings.cpp \
	$(CURDIR)/music/dialogs/GUIDialogMusicInfo.cpp \
	$(CURDIR)/music/dialogs/GUIDialogMusicOSD.cpp \
	$(CURDIR)/music/dialogs/GUIDialogSongInfo.cpp \
	$(CURDIR)/music/dialogs/GUIDialogVisualisationPresetList.cpp
