SRCS += \
	$(CURDIR)/xbmc/dialogs/GUIDialogBoxBase.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogBusy.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogBusyNoCancel.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogButtonMenu.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogContextMenu.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogColorPicker.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogExtendedProgressBar.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogFileBrowser.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogGamepad.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogKaiToast.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogKeyboardGeneric.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogMediaFilter.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogMediaSource.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogNumeric.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogOK.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogPlayEject.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogProgress.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSeekBar.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSelect.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSlider.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSmartPlaylistEditor.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSmartPlaylistRule.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSubMenu.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogTextViewer.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogVolumeBar.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogYesNo.cpp
