SRCS += \
	$(CURDIR)/xbmc/dialogs/GUIDialogBoxBase.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogOK.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSelect.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSlider.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogYesNo.cpp
