SRCS += \
	$(CURDIR)/xbmc/dialogs/GUIDialogBoxBase.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogBusy.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogContextMenu.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogExtendedProgressBar.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogGamepad.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogKaiToast.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogMediaFilter.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogNumeric.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogOK.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogProgress.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSelect.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogSlider.cpp \
	$(CURDIR)/xbmc/dialogs/GUIDialogYesNo.cpp
