SRCS += \
	$(CURDIR)/xbmc/Application.cpp \
	$(CURDIR)/xbmc/ApplicationPlayer.cpp \
	$(CURDIR)/xbmc/DatabaseManager.cpp \
	$(CURDIR)/xbmc/DbUrl.cpp \
	$(CURDIR)/xbmc/FileItem.cpp \
	$(CURDIR)/xbmc/GUIInfoManager.cpp \
	$(CURDIR)/xbmc/GUILargeTextureManager.cpp \
	$(CURDIR)/xbmc/LangInfo.cpp \
	$(CURDIR)/xbmc/ServiceBroker.cpp \
	$(CURDIR)/xbmc/ServiceManager.cpp \
	$(CURDIR)/xbmc/URL.cpp \
	$(CURDIR)/xbmc/Util.cpp \
	$(CURDIR)/xbmc/XBDateTime.cpp

include $(CURDIR)/xbmc/addons/Makefile
include $(CURDIR)/xbmc/application/Makefile
include $(CURDIR)/xbmc/commons/Makefile
include $(CURDIR)/xbmc/cores/Makefile
include $(CURDIR)/xbmc/dbwrappers/Makefile
include $(CURDIR)/xbmc/dialogs/Makefile
include $(CURDIR)/xbmc/filesystem/Makefile
include $(CURDIR)/xbmc/guilib/Makefile
include $(CURDIR)/xbmc/input/Makefile
include $(CURDIR)/xbmc/interfaces/Makefile
include $(CURDIR)/xbmc/listproviders/Makefile
include $(CURDIR)/xbmc/media/Makefile
include $(CURDIR)/xbmc/messaging/Makefile
include $(CURDIR)/xbmc/platform/Makefile
include $(CURDIR)/xbmc/settings/Makefile
include $(CURDIR)/xbmc/threads/Makefile
include $(CURDIR)/xbmc/utils/Makefile
include $(CURDIR)/xbmc/view/Makefile
