SRCS += \
	$(CURDIR)/xbmc/FileItem.cpp \
	$(CURDIR)/xbmc/LangInfo.cpp \
	$(CURDIR)/xbmc/ServiceBroker.cpp \
	$(CURDIR)/xbmc/URL.cpp \
	$(CURDIR)/xbmc/Util.cpp \
	$(CURDIR)/xbmc/XBDateTime.cpp

include $(CURDIR)/xbmc/commons/Makefile
include $(CURDIR)/xbmc/filesystem/Makefile
include $(CURDIR)/xbmc/guilib/Makefile
include $(CURDIR)/xbmc/platform/Makefile
include $(CURDIR)/xbmc/settings/Makefile
include $(CURDIR)/xbmc/threads/Makefile
include $(CURDIR)/xbmc/utils/Makefile
