SRCS += \
	$(CURDIR)/xbmc/settings/AdvancedSettings.cpp \
	$(CURDIR)/xbmc/settings/DisplaySettings.cpp \
	$(CURDIR)/xbmc/settings/LibExportSettings.cpp \
	$(CURDIR)/xbmc/settings/MediaSettings.cpp \
	$(CURDIR)/xbmc/settings/MediaSourceSettings.cpp \
	$(CURDIR)/xbmc/settings/SettingConditions.cpp \
	$(CURDIR)/xbmc/settings/SettingControl.cpp \
	$(CURDIR)/xbmc/settings/SettingDateTime.cpp \
	$(CURDIR)/xbmc/settings/SettingCreator.cpp \
	$(CURDIR)/xbmc/settings/SettingPath.cpp \
	$(CURDIR)/xbmc/settings/Settings.cpp \
	$(CURDIR)/xbmc/settings/SettingsBase.cpp \
	$(CURDIR)/xbmc/settings/SettingsComponent.cpp \
	$(CURDIR)/xbmc/settings/SettingsValueFlatJsonSerializer.cpp \
	$(CURDIR)/xbmc/settings/SettingsValueXmlSerializer.cpp \
	$(CURDIR)/xbmc/settings/SettingUtils.cpp \
	$(CURDIR)/xbmc/settings/SkinSettings.cpp

include $(CURDIR)/xbmc/settings/dialogs/Makefile
include $(CURDIR)/xbmc/settings/lib/Makefile
include $(CURDIR)/xbmc/settings/windows/Makefile
