SRCS += \
	$(CURDIR)/xbmc/settings/AdvancedSettings.cpp \
	$(CURDIR)/xbmc/settings/SettingConditions.cpp \
	$(CURDIR)/xbmc/settings/SettingControl.cpp \
	$(CURDIR)/xbmc/settings/SettingCreator.cpp \
	$(CURDIR)/xbmc/settings/SettingPath.cpp \
	$(CURDIR)/xbmc/settings/Settings.cpp \
	$(CURDIR)/xbmc/settings/SettingUtils.cpp

include $(CURDIR)/xbmc/settings/dialogs/Makefile
include $(CURDIR)/xbmc/settings/lib/Makefile
include $(CURDIR)/xbmc/settings/windows/Makefile
