SRCS += \
	$(CURDIR)/xbmc/pictures/ExifParse.cpp \
	$(CURDIR)/xbmc/pictures/GUIDialogPictureInfo.cpp \
	$(CURDIR)/xbmc/pictures/GUIViewStatePictures.cpp \
	$(CURDIR)/xbmc/pictures/GUIWindowPictures.cpp \
	$(CURDIR)/xbmc/pictures/GUIWindowSlideShow.cpp \
	$(CURDIR)/xbmc/pictures/IptcParse.cpp \
	$(CURDIR)/xbmc/pictures/JpegParse.cpp \
	$(CURDIR)/xbmc/pictures/libexif.cpp \
	$(CURDIR)/xbmc/pictures/Picture.cpp \
	$(CURDIR)/xbmc/pictures/PictureInfoLoader.cpp \
	$(CURDIR)/xbmc/pictures/PictureInfoTag.cpp \
	$(CURDIR)/xbmc/pictures/PictureScalingAlgorithm.cpp \
	$(CURDIR)/xbmc/pictures/PictureThumbLoader.cpp \
	$(CURDIR)/xbmc/pictures/SlideShowPicture.cpp
