SRCS += \
	$(CURDIR)/xbmc/music/tags/MusicInfoTag.cpp \
	$(CURDIR)/xbmc/music/tags/MusicInfoTagLoaderCDDA.cpp \
	$(CURDIR)/xbmc/music/tags/MusicInfoTagLoaderDatabase.cpp \
	$(CURDIR)/xbmc/music/tags/MusicInfoTagLoaderFactory.cpp \
	$(CURDIR)/xbmc/music/tags/MusicInfoTagLoaderFFmpeg.cpp \
	$(CURDIR)/xbmc/music/tags/MusicInfoTagLoaderShn.cpp \
	$(CURDIR)/xbmc/music/tags/ReplayGain.cpp \
	$(CURDIR)/xbmc/music/tags/TagLoaderTagLib.cpp
